[build]
  command = "npm run build && mkdir -p .output/public"
  publish = ".output/public"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--include=dev"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
